### PR TITLE
Update package.json to update moment

### PR DESCRIPTION
**Pull request by justinffs**
See security advisory https://nodesecurity.io/advisories/532

### CODE REVIEW

**Comment by Marsup** [comment]
Dupe of #98.

**Comment by justinffs** [comment]
I agree this is a dupe but #98 updates lab as well.
Not sure why there is a delay in getting this security issue addressed and into NPM #98 makes unecessary changes

**Comment by Marsup** [comment]
Your tests fail in case you didn't notice, this is the reason why.
There is a delay because the maintainer is human and apparently has a life, sorry.

**Comment by justinffs** [comment]
Apologies, that isn't what I meant.  I didn't realize that the test were broken and need to be fixed for other reasons.  I assumed that the additional changes not related and causing a delay.

**Pull request closed without merging**
