### PR TITLE
add requestPayload to response message

### PR DESCRIPTION
**Pull request by CristiScheye**
Our team needed a way of logging request payloads, so this is the solution I came up with. Not sure if there's another way to do this with existing code (lmk if there is :) ). Thanks!

### CODE REVIEW

**Comment by lloydbenson** [comment]
Have you looked into the good-file module?  The idea behind good-console I think is to keep it relatively slim but you can use good-file to get lots of additional logging.  If you look at the good documentation you can already set requestPayload to true if you want that additional information.

**Comment by arb** [comment]
Logging this much information to the console isn't really a good idea. Any reason you can't just log to a file?

**Comment by kevyau** [comment]
+1 on this PR. 

I've noticed that there have been a few similar PR's regarding requestPayload and requestHeader that have been closed:
* https://github.com/hapijs/good-console/pull/32
* https://github.com/hapijs/good-console/pull/37
* https://github.com/hapijs/good-console/pull/41 

Also it was discussed here: https://github.com/hapijs/good-console/issues/36

Unfortunately we are in a similar boat as @nackjicholson, where we have containerized our hapi app and forward stdout to our log system. In this scenario it's more ideal to use good-console than good-file as we don't want to keep rotating log files in our containers. 

I do appreciate the argument to keep good-console streamline though, if there is no way forward would it be possible to update the readme to clarify the optional properties (header, requestPayload, requestHeader) mentioned in the [Good readme](https://github.com/hapijs/good#greatresponserequest-options) is not supported in this reporter, at least for consistency ?

**Comment by arb** [comment]
How about good-http? Then you could have all your containers send their logs to a centralized HTTP server.

As far as the good documentation is concerned, it says

> [requestHeaders] - determines if all request headers will be available to reporter objects. (...)
> [requestPayload] - determines if the request payload will be available to reporter objects. (...)
> [responsePayload] - determines if the response payload will be available to reporter objects. (...)

Only says these values will be *available* to reporter objects, not that they will be included in every logging activity.

**Comment by CristiScheye** [comment]
@lloydbenson thanks for pointing out good-file, I'll check it out!

I'm curious about the reasoning behind not wanting to include the request payload though. If the response payload is already being logged, the request payload seems like a small but very helpful addition (e.g. when debugging a failed request).

**Comment by ben-ng** [comment]
Apps running on PaaS'es don't really have the option of writing to a file.

Logged request payloads have been really helpful for debugging errors in our app, since they usually contain everything we need to reproduce a problem.

**Comment by arb** [comment]
good-console is not intended for large payloads like this. Either create your own customized console logger or try one of the other suggestions here. Reporters are trivial to write, so creating your own wouldn't be hard. If you want it added to the list of reporters, open an PR in the good repository.

**Pull request closed without merging**
