### PR TITLE
Log headers and request payload too

### PR DESCRIPTION
**Pull request by ejeklint**
If logRequestHeaders and logRequestPayload is true in good's options, they should be logged. I added that and two new tests.

### CODE REVIEW

**Comment by ejeklint** [comment]
Now that I got a minute to reflect - it's a bit odd to add request headers and payload to good's response event, but that's where good puts it now. So, in lieu of a change in good, maybe this can work for now?

**Comment by arb** [comment]
I question how useful this is really going to be... adding ALL of that stuff into the console seems like way overkill unless you have like a 60 inch screen.

I sort of feel like if anything, this should be additional options into good-console rather than assuming the options from good pass down into good-console. Not only is that not documented, but sort of increases the coupling between the two modules. 

Now that you mention it, those options should probably be renamed to `record`XXX since good doesn't do any logging anymore.

**Comment by ejeklint** [comment]
Well from the users point of view there should be a way to see all that if they use good for monitoring and good-console as only reporter. After all, the options to good are what the user see and can set. But maybe one should be able to set the options on the reporters as well, so one can override the topmost good settings if one uses more than one reporter and need separate settings for them.

**Comment by arb** [comment]
Please make logging this stuff controlled via options and default them to `false` so it's not a breaking change.

**Comment by arb** [comment]
Closing due to inactivity.

**Comment by jondlm** [comment]
Dang, I was hoping to see this go in. I was about to write a PR myself.

There are plenty of debugging cases where you need to see headers and payloads. It really confused me to be able to set the flags at the *good* level and not have them respected by *good-console*.

**Comment by arb** [comment]
Those settings will probably renamed because it _is_ confusing to see the word `log` and not have it actually log. A PR moving that logic into good-console will be fine. This was closed because the required changes were not made.

**Pull request closed without merging**
